version: "2"
services:
  app:
    container_name: catonline_app
    restart: always
    build: .
    command: nodemon -L server.js
    ports:
      - "49160:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb:://mongo:27017/catonline-db
    volumes:
      - .:/usr/src/app/
      - /usr/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
