version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    command: "--smallfiles"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: catonline_app
    restart: always
    build: .
    command: nodemon -L server.js --ignore data/* --ignore tests/* --ignore public/*
    ports:
      - "49160:3000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app/
      - /usr/app/node_modules
