#!/usr/bin/env python3

# pip3 install requests
import csv, json, os, re, requests, sys

def get_sheet( spreadsheet, gid ):
    obj = []
    url = "https://spreadsheets.google.com/feeds/download/spreadsheets/Export?key=%s&exportFormat=tsv&gid=%s" % (spreadsheet, gid)
    res = requests.get(url)
    if res.status_code == 200:
        content = res.content.decode('utf-8')
        lines = content.split('\r\n')
        for line in lines:
            obj.append( line.split('\t') )
        return obj
    else:
        print( 'exiting ... HTTP response %s at `%s`' % (res.status_code, url) )
        exit()

def get_sheets( spreadsheet, sheets ):
    data = {}
    for sheet in sheets:
        data[sheet] = get_sheet( spreadsheet, sheets[sheet] )
    return data

def get_state_graph():

    spreadsheet = "1UlTewbihkhtMcIgH6p1RqhkqUcSufclM7UvAu6EgOcI"
    sheets = {
        'vertices'  : "235763305",
        'edges'     : "931117447"
    }

    sheets = get_sheets( spreadsheet, sheets )
    data = { 'vertices':{}, 'edges':{} }
    ignoreList = [ 'id' ]

    isHeader = True
    for line in sheets['vertices']:
        if isHeader:
            header = line
            isHeader = False
        else:
            for i in range(len(line)):
                col_name = header[i]
                if col_name == 'name':
                    vertex_name = replace_name( 'v', line[i] )
                    data['vertices'][vertex_name] = { 'edges':[] }
                elif col_name not in ignoreList:
                    data['vertices'][vertex_name][col_name] = line[i]
    isHeader = True
    for line in sheets['edges']:
        if isHeader:
            header = line
            isHeader = False
        else:
            for i in range(len(line)):
                col_name = header[i]
                if col_name == 'name':
                    edge_name = replace_name( 'e', line[i] )
                    data['edges'][edge_name] = {}
                elif col_name == 'source':
                    vertex_name = replace_name( 'v', line[i] )
                    data['vertices'][vertex_name]['edges'].append( edge_name )
                elif col_name == 'target':
                    vertex_name = replace_name( 'v', line[i] )
                    data['edges'][edge_name][col_name] = vertex_name
                elif col_name.startswith('is'):
                    data['edges'][edge_name][col_name] = len(line[i])>0
                elif col_name not in ignoreList:
                    data['edges'][edge_name][col_name] = line[i]

    data = json.dumps(data,indent=3)
    for item in [ 'vertices', 'edges', 'evaluate', 'execute', 'isMulti', 'isPriority', 'isCancel', 'target', 'label' ]:
        data = re.sub( '"%s"' % item, '%s' % item, data )
    data = re.sub(r'"(func.*\})"', r'\1', data)

    filepath = get_filepath( os.path.join('config','states') )
    with open(filepath, 'w') as f:
        data = 'module.exports = %s' % data
        f.write(data)

    return

def get_filepath( moduledge_name ):
    return os.path.join( os.path.dirname(sys.argv[0]), '..', '%s.js' % moduledge_name )

def replace_name( prefix, name ):
    return '_%s_%s' % ( prefix, name.replace(' ','_') )

if __name__ == '__main__':

    if len(sys.argv)==1:
        get_state_graph()

    elif (sys.argv[1]=='states'):
        get_state_graph()

    else:
        print( 'Error: no action matching argument "%s"' % sys.argv[1] )
